name: hello-world
on: push
jobs:
  my-job: 
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "hello world"
      - name: Install dependencies
        run: python -m pip install --upgrade pip
      - name: Checkout code
        uses: actions/checkout@v3
